apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
spec:
  selector:
    app: valkey
  ports:
    - name: client
      port: 6379
      targetPort: 6379
    - name: cluster
      port: 16379
      targetPort: 16379
    - name: metrics
      port: 9121
      targetPort: 9121
  clusterIP: None